### ISSUE TITLE
Report not possible during time-shift

### ISSUE THREAD

**Issue by jakobbraun** [exasol/cloudwatch-adapter#2]
In case your Exasol database uses a timezone with a time-shift as `DBTIMEZONE`, this adapter will **not report** the hour when the time is shifted back, since Exasol stores the statistics entries in the `DBTIMEZONE` and by that, the log entries are ambiguous in that hour.

Steps for Fix:

- [ ] Change column `EXA_STATISTICS` table to use `TIMESTAMP WITH LOCAL TIMEZONE` instead of `TIMESTAMP` or store entries in UTC.
- [ ]  Change this adapter to use the new API

**Comment by redcatbear** [comment]
@jakobbraun: I don't see this happening in the core anytime soon. Please write into the user guide as known limitation and close the ticket.

**Comment by jakobbraun** [comment]
It's already there: https://github.com/exasol/cloudwatch-adapter#known-bugs
