### ISSUE TITLE
I don't see metrics collected

### ISSUE THREAD

**Issue by jorge-delgado-aera** [exasol/cloudwatch-adapter#60]
Hello,

I have installed cloudwatch-adapter for exasol (DB version 7.1.6), currently I just see these messages in cloudwatch:

- sun.reflect.Reflection.getCallerClass is not supported. _This will impact performance.

- Transforming org/apache/logging/log4j/core/lookup/JndiLookup (lambdainternal.CustomerClassLoader@433c675d)

-  START RequestId: bbf47e5c-7f52-4e5a-b58a-25dd37c8027b Version: $LATEST

- 2022-03-20 18:40:14 bbf47e5c-7f52-4e5a-b58a-25dd37c8027b INFO CloudWatchAdapter - Writing 108 points.

- END RequestId: bbf47e5c-7f52-4e5a-b58a-25dd37c8027b

- REPORT RequestId: bbf47e5c-7f52-4e5a-b58a-25dd37c8027b Duration: 4497.37 ms Billed Duration: 4498 ms Memory Size: 512 MB Max Memory Used: 184 MB Init Duration: 4733.76 ms

**Checking inside of DB I just see these commands performed by user CLOUDWATCH_ADAPTER ** 

- SELECT NOW()

- SELECT CONVERT_TZ(MEASURE_TIME, DBTIMEZONE, 'UTC', 'INVALID REJECT AMBIGUOUS REJECT') as UTC_MEASURE_TIME, t.* FROM "EXA_STATISTICS"."EXA_DB_SIZE_LAST_DAY" t WHERE MEASURE_TIME >= CONVERT_TZ(?, 'UTC', DBTIMEZONE, 'INVALID REJECT AMBIGUOUS REJECT') AND MEASURE_TIME < CONVERT_TZ(?, 'UTC', DBTIMEZONE, 'INVALID REJECT AMBIGUOUS REJECT');

- COMMIT /* AUTO */

-ALTER SESSION SET TIME_ZONE = 'UTC'

**Comment by jakobbraun** [comment]
That sounds good so far. 
Now you should be able to discover the metrics. As a start I  recommend using our [example dashboard](https://github.com/exasol/cloudwatch-dashboard-examples/).

**Comment by jorge-delgado-aera** [comment]
Thanks @jakobbraun, I could see the metrics now displayed in dashboard, will be testing this and any concern will let you know.

**Comment by jakobbraun** [comment]
Great. If you should come across an issue fell free to open a ticket again.
