### ISSUE TITLE
Information doesn't match with ExaOperation

### ISSUE THREAD

**Issue by jorge-delgado-aera** [exasol/cloudwatch-adapter#61]
hello, I'm comparing the information collected by metrics vs information showed in exa operation and it doesn't match, could you guide me for this

**Comment by jakobbraun** [comment]
Hi, which information are you comparing?

**Comment by jorge-delgado-aera** [comment]
Persistent storage usage, storage size

![image](https://user-images.githubusercontent.com/90013150/164552494-fc304190-d6b8-42b5-8526-b9113e425316.png)

![image](https://user-images.githubusercontent.com/90013150/164553864-7612e88a-f7fb-49fc-a9f0-c464a37cb608.png)


![image](https://user-images.githubusercontent.com/90013150/164552778-8face885-a2d0-4480-862a-b0455db3f509.png)

**Comment by jakobbraun** [comment]
I see. The CloudWatch adapter copies the metrics from the [Exasol system tables](https://docs.exasol.com/db/latest/sql_references/system_tables/statistical_system_tables.htm). 
First here some generic information:
CloudWatch then aggregates them over the configured time window. You can see / configure the used aggregation function in the settings of the widget in the dashboard.
In addition, the adapter converts the values from GiB to GB.

Could you please check if the values shown on your dashboard match with those from the statistic tables? 

If that's the case, this integration works correctly. Then please open a support ticket to clarify the meaning of the numbers.

**Comment by jorge-delgado-aera** [comment]
thanks @jakobbraun, I checked the values in EXA_DB_SIZE_HOURLY and information match if I convert from GigaBytes (GB) to (Gigibytes), just another doubt, do you know why sometimes information is not showed if a select different timeframe, below an example of this

![image](https://user-images.githubusercontent.com/90013150/165441111-fc0d9e1a-f29b-467a-a54b-2bc66c21ed8d.png)

![image](https://user-images.githubusercontent.com/90013150/165441156-11d40358-f38f-48cc-a757-f1c6e7853f14.png)

**Comment by jorge-delgado-aera** [comment]
hi @jakobbraun, could it be modified to collect temp_size and memory object size every one minute, my justification is that I' m programming alarms for this, usually users and applications use a lot of temp_size and I want to receive alarms in real time if total storage used is above of 90% for warning and 95% for critical, if these values are collected every 5 minutes or more it is time spent without any action in DB and it could provoke an outage, thanks in advance for all your help, REGARDS!

**Comment by redcatbear** [comment]
@jorge-delgado-aera, the Cloud Watch connector takes its data from [Exasol's statistics tables](https://docs.exasol.com/db/latest/sql_references/system_tables/statistical_system_tables.htm) by polling them. All statistical tables are aggregates over certain timeframes. The finest granularity is one hour.

There is a table [EXA_STATISTICS_OBJECT_SIZES](https://docs.exasol.com/db/latest/sql_references/system_tables/metadata/exa_statistics_object_sizes.htm) where the documentation seems to indicate that it holds the current value. But I suspect that once-per minute polling is going to be expensive. @jakobbraun, can you confirm my guess?

**Comment by jakobbraun** [comment]
I can totally understand your need for a higher time resolution here.
The adapter copies those metrics from EXA_DB_SIZE_LAST_DAY. In fact, it polls from there once a minute, but the database only writes entries every 30 minutes. That's why also the adapter only reports a value in those intervals.
So the only way to change this is to make the DB report the statistics more often. However, I checked this with our core-db team and currently its not possible.

**Comment by exaSR** [comment]
The system tables in EXA_STATISTICS are meant to provide a stable timeline for retrospective analysis.

If your need goes more into operational monitoring, I would suggest you use non-aggregated "current value" sources like [SYS.EXA_VOLUME_USAGE](https://docs.exasol.com/db/latest/sql_references/system_tables/metadata/exa_volume_usage.htm).

**Comment by jakobbraun** [comment]
I created a follow-up ticket: #69

**Comment by jakobbraun** [comment]
I'm closing this issue since the original question is solved.
