### ISSUE TITLE
No backup metrics collected

### ISSUE THREAD

**Issue by jorge-delgado-aera** [exasol/cloudwatch-adapter#70]
Previously of the new version released I saw 32 metrics collected, but after the upgrade I still see the same 32 metrics, do I need to perform anything else to see backup metrics or any new metric added?, below the link for metrics that I refer to.

[https://github.com/exasol/cloudwatch-adapter/blob/main/doc/changes/changes_1.0.0.md#cloudwatch-adapter-100-released-2022-02-23](https://github.com/exasol/cloudwatch-adapter/issues/url)

As your team suggested in other ticket I have validated information in table EXA_SYSTEM_EVENTS

<img width="950" alt="image" src="https://user-images.githubusercontent.com/90013150/166460039-733b35e0-f823-4622-944f-3706595f2b85.png">

**Comment by kaklakariada** [comment]
Hi @jorge-delgado-aera ,
thank you for creating a new issue for this! The data from your `EXA_SYSTEM_EVENTS` looks good.
The cloudwatch-adapter's lambda function runs every minute and creates metrics for the values from the previous minute in order to avoid reporting data multiple times. That's why it's important that the lambda runs every minute.

Please check the following:
* Verify that other metrics for your Exasol database are up-to-date
* Verify that the lambda named `cloudwatch-adapter-*` runs successfully every minute. The metrics for the lambda should look like this: 
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/4711730/166866931-20e5109a-b25c-476c-9fd1-1cb2cc27c120.png">
* Check that the timestamps in the invocation log are up-to-date and increment every minute:
<img width="1359" alt="Screenshot 2022-05-05 at 07 20 46" src="https://user-images.githubusercontent.com/4711730/166867340-a665734d-1c76-4ca7-8eab-bbc5f3d9bd41.png">

When did you install/update the cloudwatch-adapter? It won't report backup events from the past.

**Comment by kaklakariada** [comment]
Hi  @jorge-delgado-aera ,
Thank you for sending the screenshots! In the error count diagram of the lambda I can see some small error spikes. Could you please send the log of the latest failed invocation? Maybe there is a bug in the lambda that causes metrics collection to fail for backup events.

Also I can see the execution time goes up to 100s (the configured timeout) when the lambda fails. It's possible that the execution of the lambda takes a longer time for your Exasol database. Please go the Configuration section and increase the timeout to 10 minutes. Then wait until the next backup finishes and check if the event metric is created.

**Comment by jorge-delgado-aera** [comment]
hi @kaklakariada,

I have checked about the error, it seems timeout, below the screenshots and also log attached.
![image](https://user-images.githubusercontent.com/90013150/167801781-35d9636c-e463-4b2a-bf0d-35ee1695240f.png)

![image](https://user-images.githubusercontent.com/90013150/167801954-aa2608c9-a9d1-4922-b6a8-b40edc07ecdb.png)

[log-events-viewer-result (1).csv](https://github.com/exasol/cloudwatch-adapter/files/8667996/log-events-viewer-result.1.csv)

**Comment by kaklakariada** [comment]
Hi @jorge-delgado-aera ,

Looks like one of the queries used by the cloudwatch adapter is slow. Please run the following query to find the long running queries:

```sql
select a.*
from EXA_DBA_AUDIT_SQL a join EXA_DBA_SESSIONS s on a.session_id = s.session_id
where s.user_name = '<user>'
order by a.duration desc;
```

Please insert the database user you configured for the cloudwatch adapter. This will help us find the slow query.

Please also run this query (again with the correct user) to check if the cloudwatch adapter is up-to-date and sends the correct queries:

```sql
select a.*
from EXA_DBA_AUDIT_SQL a join EXA_DBA_SESSIONS s on a.session_id = s.session_id
where s.user_name = '<user>'
order by a.start_time desc;
```

**Comment by jorge-delgado-aera** [comment]
hi @kaklakariada, above script didn't retrieve data, but I ran below ones and I got the next info:

`select a.command_name, command_class, duration, start_time, sql_text
from EXA_DBA_AUDIT_SQL a join EXA_DBA_AUDIT_SESSIONS s on a.session_id = s.session_id
where s.user_name = 'CLOUDWATCH_ADAPTER'
AND A.EXECUTION_MODE<>'PREPROCESS'
order by a.duration desc;`

![image](https://user-images.githubusercontent.com/90013150/168974936-77cd3121-f5c3-4e62-bc82-40e7a409e56b.png)

`select DISTINCT sql_text
from EXA_DBA_AUDIT_SQL a join EXA_DBA_AUDIT_SESSIONS s on a.session_id = s.session_id
where s.user_name = 'CLOUDWATCH_ADAPTER'`

![image](https://user-images.githubusercontent.com/90013150/168975421-5789f0b6-344a-4cdd-a249-53b6f6d194f6.png)

**Comment by kaklakariada** [comment]
Hi @jorge-delgado-aera ,
thank you for your reply! It is strange that a simple `SELECT NOW()` takes 47s. Is it possible that the database is under heavy load?
From the second query result I can see that the query for retrieving the backup duration is not executed. Can you please check if the relevant backup metrics are configured for the lambda?

* [`EVENT_BACKUP_END`](https://docs.exasol.com/db/latest/sql_references/system_tables/statistical/exa_system_events.htm)
* [`EVENT_BACKUP_START`](https://docs.exasol.com/db/latest/sql_references/system_tables/statistical/exa_system_events.htm)
* [`EVENT_BACKUP_ABORTED`](https://docs.exasol.com/db/latest/sql_references/system_tables/statistical/exa_system_events.htm)
* [`BACKUP_DURATION`](https://docs.exasol.com/db/latest/sql_references/system_tables/statistical/exa_system_events.htm)

<img width="1354" alt="Screenshot 2022-05-18 at 10 40 04" src="https://user-images.githubusercontent.com/4711730/168997780-31cb7915-e671-46d4-8783-89fbd670b2c9.png">

If the events are missing you can add them directly in the Lambda configuration or as described in the [readme](https://github.com/exasol/cloudwatch-adapter#setup-cloudwatch-adapter).

**Comment by jorge-delgado-aera** [comment]
thanks @kaklakariada, these metrics were not in the configuration, recently I added it, will let you know if these work correctly :)

**Comment by jorge-delgado-aera** [comment]
hi @kaklakariada, after I added such metrics all metrics are failing, checking in logs I see below message

_E-CWA-31: Invalid metrics [EVENT_BACKUP_ABORTED, EVENT_BACKUP_START, EVENT_BACKUP_END, BACKUP_DURATION]. This adapter can report the following metrics: ['RECOMMENDED_DB_RAM_SIZE', 'PERSISTENT_DB_RAM', 'LOAD', 'TEMP_SIZE', 'LOCAL_WRITE_DURATION', 'CPU', 'RAW_OBJECT_SIZE', 'HDD_READ', 'HDD_WRITE', 'LOCAL_READ_SIZE', 'CACHE_READ_DURATION', 'CACHE_READ_SIZE', 'OBJECT_COUNT', 'QUERIES', 'TEMP_DB_RAM', 'NODES', 'CACHE_WRITE_DURATION', 'MEM_OBJECT_SIZE', 'USE', 'AUXILIARY_SIZE', 'REMOTE_WRITE_DURATION', 'DB_RAM_SIZE', 'LOCAL_READ_DURATION', 'REMOTE_WRITE_SIZE', 'STATISTICS_SIZE', 'CACHE_WRITE_SIZE', 'SWAP', 'STORAGE_SIZE', 'REMOTE_READ_SIZE', 'NET', 'USERS', 'REMOTE_READ_DURATION', 'NODES', 'DB_RAM_SIZE']_

![image](https://user-images.githubusercontent.com/90013150/169531299-e9e05863-c583-4a43-ae4a-1c183c1f72ef.png)

**Comment by kaklakariada** [comment]
Hi @jorge-delgado-aera ,
This looks like the Lambda does not support the new metrics. Is it possible that this is still an older version of the cloudwatch adapter Lambda? Please install the latest version 1.0.1 which supports the new backup metrics.

**Comment by jorge-delgado-aera** [comment]
thanks @kaklakariada, is there a documented process for following up of correct steps

**Comment by kaklakariada** [comment]
Hi @jorge-delgado-aera ,
The installation AWS' serverless application repository is described [here](https://github.com/exasol/cloudwatch-adapter#setup).

**Comment by jorge-delgado-aera** [comment]
Thanks @kaklakariada, I have deployed the metrics for other cluster and now I can see metrics for backups

**Comment by kaklakariada** [comment]
Thank you for the feedback, great that it works now!
I will close this issue now. Don't hesitate to create a new issue if other problems occur!
